### ISSUE TITLE
The spatial coherence matrix in sphiPMMW.m

### ISSUE THREAD

**Issue by jieyangzhang** [polarch/Spherical-Array-Processing#6]
Hello, dear plarch:
    I am reading paper "An Informed Parametric Spatial Filter Based on Instantaneous Direction-of-Arrival Estimates" recently, and I found your Simulation Code in this repository.And I have some question while viewing your code.
    1) In the paper, the equation (33b) calculating the diffuse sound power and I found the code(line:53 in sphiPMMW.m) which missing the spatial coherence matrix in denominator. Why the spatial coherence matrix can be ignored? Is it Insignificant in the algorithm?
    2) Why the code which calculating the second order statistic of diffuse signal and noise signal (line:60 in sphiPMMW.m) missing spatial coherence matrix too, and there is (4*pi) part in denominator.
    I feel confused in these two question for few days, I hope you can help me understand.
Looking forward to your answer ! Thank you !

**Comment by polarch** [comment]
Hi jieyangzhang,

Maybe the name pMMW here is a bit misleading, since if I remember correctly in Thiergart's paper there was plenty of work to decide on optimal noise-to-diffuse power ratios, and such, while here there is no (sensor) noise assumed, just directional (plane wave) sources and an isotropic diffuse component.

However, to answer your questions - the spatial coherence matrix is missing in the denominator because in the psherical harmonic domain, for isotropic diffuse fields, it is a scaled identity matrix, which vanishes in the formula.

**Comment by jieyangzhang** [comment]
Thanks for your reply!
Oh, I understand, you chose a scaled identity matrix as the spatial coherence matrix in equation (33a), but where is the scale number?
And why there is a (4 * pi) in line:60 in sphiPMMW.m.

**Comment by polarch** [comment]
Hi jieyangzhang,

The scale number disappears after an identity diffuse coherence matrix assumption. The 4pi is coming from the properties of the spherical harmonics.

**Comment by jieyangzhang** [comment]
OK, I understand now. Thank you again!
